name: Quick test

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    # Run on external PRs, but not on internal PRs, to avoid duplicate runs
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    runs-on: "macos-14"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-bdist/
        with:
          cibw-only: "cp313-macosx_arm64"
          upload-name: build-wheels-cp313-macosx_arm64

  run-tests:
    needs: build
    runs-on: "macos-14"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-tests/
        with:
          python-version: "3.13"
          nox-session: "test"
          pytest-addopts: "-m 'not slow and not richdem'"
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  run-notebooks:
    needs: build
    runs-on: "macos-14"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-notebooks/
        with:
          python-version: "3.13"
          nox-session: "test-notebooks"
          pytest-addopts: "--overwrite -m 'not slow and not richdem'"
          opentopography-api-key: ${{ secrets.OPENTOPOGRAPHY_API_KEY }}
